# Copyright (C) 2022 Guilherme Janczak <guilherme.janczak@yandex.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies of the Software and its documentation and acknowledgment shall be
# given in the documentation and software packages that this Software was
# used.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

common_template: &common_script
  build_script:
    - if command -v ccomp; then
    -   export native_file=--native-file=.github/workflows/meson-compcert.txt
    - fi
    - meson setup $native_file -Dtest_system=true build
    - meson compile -C build
  test_script:
    - meson test --no-suite system -C build
  test_system_script:
    - meson test --suite system -C build || true
  install_script:
    - meson install -C build
  on_failure:
    termux-meson-logs_artifacts:
      path: build/meson-logs

task:
  container:
    image: alpine:latest
    kvm: true
  name: musl
  setup_script:
    - apk add meson alpine-sdk clang
  << : *common_script

task:
  container:
    image: artixlinux/base
    kvm: true
  name: compcert
  aur_script:
    - printf '%s\n%s\n' '[xuanrui]'
             'Server = https://www.math.nagoya-u.ac.jp/~x18004y/repo/'
             >> /etc/pacman.conf
    - pacman-key --init
    - pacman-key --recv-keys 6E06FBC8
    - pacman-key --lsign-key 6E06FBC8
  setup_script:
    - pacman --noconfirm -Syu compcert ninja meson git
  << : *common_script

task:
  freebsd_instance:
    # Keep updated with newest release from https://www.freebsd.org/releases/
    image: freebsd-13-1-release-amd64
  name: freebsd
  setup_script:
    - pkg install -y meson ninja gcc
  << : *common_script

task:
  container:
    image: kcubeterm/termux:x86_64
    kvm: true
  name: bionic
  setup_script:
    - pkg install -y ninja clang python
    - pip install meson
  << : *common_script
