.\"	$OpenBSD: mdoc.template,v 1.15 2014/03/31 00:09:54 dlg Exp $
.\"
.\" Copyright (c) 2022 Guilherme Janczak <guilherme.janczak@yandex.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: April 12 2022 $
.Dt GETPROGNAME 3
.Os
.Sh NAME
.Nm getprogname
.Nd get program name
.Sh SYNOPSIS
.In stdlib.h
.Ft const char *
.Fn getprogname "void"
.Sh DESCRIPTION
The
.Fn getprogname
function returns a pointer to a statically allocated string containing the
program's name.
The program's name is the last component of the path to its executable.
If the program was called through a symlink, the program's name is the symlink's
name.
.Pp
The name is the same name used by the
.Xr err 3
family of functions.
.Sh RETURN VALUES
The
.Fn getprogname
function always returns a non-null pointer.
.Sh SEE ALSO
.Xr err 3
.Sh CAVEATS
The program's name can be set by a parent process.
The string does not guarantee that the current program is the program it
suggests.
