# Copyright (c) 2022 Guilherme Janczak <guilherme.janczak@yandex.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

name: Build and test
on: [push, pull_request]

# GitHub Actions doesn't support YAML anchors, so the bit of code below is
# copypasted between jobs:
#
#      - uses: actions/checkout@v2.4.0
#      - name: build
#        run: |
#          meson setup -Dtest_system=true build
#          meson compile -C build
#      - name: test
#        run: meson test --no-suite system -C build
#      - name: test_system
#        run: meson test --suite system -C build || true
#      - uses: actions/upload-artifact@v2.3.1
#        if: failure()
#        with:
#          name: meson-logs
#          path: build/meson-logs

jobs:
  dietlibc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.3.1
      - name: setup
        run: |
          pip install meson ninja
          sudo apt install -y dietlibc-dev
      - uses: actions/checkout@v2.4.0
      - name: build
        run: |
          CC='diet gcc' meson setup -Dtest_system=true \
                        -Ddefault_library=static       \
                        build
          meson compile -C build
      - name: test
        run: meson test --no-suite system -C build
      - name: test_system
        run: meson test --suite system -C build || true
      - uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: dietlibc-meson-logs
          path: build/meson-logs
  glibc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2.3.1
      - name: setup
        run: |
          pip install meson ninja
          sudo apt install -y dietlibc-dev
      - uses: actions/checkout@v2.4.0
      - name: build
        run: |
          meson setup -Dtest_system=true build
          meson compile -C build
      - name: test
        run: meson test --no-suite system -C build
      - name: test_system
        run: meson test --suite system -C build || true
      - uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: glibc-meson-logs
          path: build/meson-logs
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/setup-python@v2.3.1
      - run: pip install meson ninja
      - uses: actions/checkout@v2.4.0
      - name: build
        run: |
          meson setup -Dtest_system=true build
          meson compile -C build
      - name: test
        run: meson test --no-suite system -C build
      - name: test_system
        run: meson test --suite system -C build || true
      - uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: macos-meson-logs
          path: build/meson-logs
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        sys: [mingw64, mingw32, ucrt64, clang64]
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          release: false
          update: false
          path-type: strict
          install: git
          pacboy: >-
            gcc:p clang:p meson:p ninja:p
      - uses: actions/checkout@v2.4.0
      - name: build
        run: |
          meson setup -Dtest_system=true build
          meson compile -C build
      - name: test
        run: meson test --no-suite system -C build
      - name: test_system
        run: meson test --suite system -C build || true
      - uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: ${{matrix.sys}}-meson-logs
          path: build/meson-logs
  MSYS:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          release: false
          update: false
          path-type: strict
          install: git gcc clang meson ninja
      - uses: actions/checkout@v2.4.0
      - name: build
        run: |
          meson setup -Dtest_system=true build
          meson compile -C build
      - name: test
        run: meson test --no-suite system -C build
      - name: test_system
        run: meson test --suite system -C build || true
      - uses: actions/upload-artifact@v2.3.1
        if: failure()
        with:
          name: msys-meson-logs
          path: build/meson-logs
