# Copyright (c) 2022-2025 Guilherme Janczak <guilherme.janczak@yandex.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

name: 'Integration Testing'
on: [push, pull_request]

jobs:
  msys2:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    strategy:
      matrix:
        sys: [msys, mingw64, mingw32, ucrt64, clang64]
        link: [shared, static]
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          path-type: strict
          pacboy: |
            gcc:p meson:p ninja:p pkgconf:p groff: dos2unix:
      - uses: actions/checkout@v4.2.2 # checkout libobsd
      - uses: actions/checkout@v4.2.2 # checkout dictpw
        with:
          repository: guijan/dictpw
          path: dictpw
      - run: winget install --id JRSoftware.InnoSetup -e -s winget -h
        shell: powershell
      - name: ${{matrix.link}} test
        run: |
          # Meson's default destdir on MSYS isn't in pkgconf's default search 
          # path.
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
          inno="$(cmd //c 'echo %LocalAppData%')\\Programs\\Inno Setup 6\\"
          inno="$(cygpath -u "$inno")"
          PATH="${PATH}:${inno}"
          echo "$PATH"
          meson setup build -Db_lto=false -Dprovide_libbsd=true \
            -Ddefault_library=${{matrix.link}}
          meson install -C build
          cd dictpw
          meson setup build -Db_lto=false --wrap-mode=nofallback
          meson compile -C build
      - uses: actions/upload-artifact@v4.5.0
        if: always()
        with:
          name: meson-logs-int-${{matrix.sys}}-${{matrix.link}}
          path: |
            build/meson-logs
